In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Candidatos.csv')

In [ ]:
df.head()

,ano,id_eleicao,tipo_eleicao,data_eleicao,sigla_uf,id_municipio,id_municipio_tse,titulo_eleitoral,cpf,sequencial,...,idade,genero,instrucao,ocupacao,estado_civil,nacionalidade,sigla_uf_nascimento,municipio_nascimento,email,raca
0,1998,1998001,eleicao ordinaria,1998-10-04,MG,NaN,NaN,3.098924e+10,2.756347e+10,130001307336031,...,41.0,masculino,NaN,proprietario de estabelecimento comercial,casado(a),brasileira,NaN,NaN,NaN,NaN
1,1998,1998001,eleicao ordinaria,1998-10-04,RO,NaN,NaN,4.870823e+08,2.643049e+09,220002210002211,...,44.0,masculino,ensino medio completo,proprietario de estabelecimento comercial,solteiro(a),brasileira,AC,Tarauaca,NaN,NaN
2,1998,1998001,eleicao ordinaria,1998-10-04,AC,NaN,NaN,8.284125e+08,9.138374e+09,100000106011011,...,38.0,masculino,ensino superior incompleto,membros do poder legislativo: senador deputado...,divorciado(a),brasileira,AC,Feijo,NaN,NaN
3,1998,1998001,eleicao ordinaria,1998-10-04,AC,NaN,NaN,2.475425e+08,6.665543e+09,100000106025331,...,52.0,masculino,ensino superior completo,advogado,casado(a),brasileira,AC,Rio Branco,NaN,NaN
4,1998,1998001,eleicao ordinaria,1998-10-04,AC,NaN,NaN,4.027244e+07,1.546503e+09,100000107111091,...,52.0,masculino,ensino medio incompleto,membros do poder executivo: presidente ministr...,divorciado(a),brasileira,AC,Feijo,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104590 entries, 0 to 104589
Data columns (total 28 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ano                   104590 non-null  int64
 1   id_eleicao            104590 non-null  int64
 2   tipo_eleicao          104590 non-null  object
 3   data_eleicao          104590 non-null  object
 4   sigla_uf              104578 non-null  object
 5   id_municipio          91009 non-null   float64
 6   id_municipio_tse      91013 non-null   float64
 7   titulo_eleitoral      103307 non-null  float64
 8   cpf                   90128 non-null   float64
 9   sequencial            104590 non-null  int64
 10  numero                104590 non-null  int64
 11  nome                  104590 non-null  object
 12  nome_urna             103222 non-null  object
 13  numero_partido        104590 non-null  int64
 14  sigla_partido         104590 non-null  object
 15  cargo                 104590 non-null  object
 16  situacao              100313 non-null  object
 17  data_nascimento       104526 non-null  object
 18  idade                 104520 non-null  float64
 19  genero                103323 non-null  object
 20  instrucao             102596 non-null  object
 21  ocupacao              102654 non-null  object
 22  estado_civil          102590 non-null  object
 23  nacionalidade         102629 non-null  object
 24  sigla_uf_nascimento   102627 non-null  object
 25  municipio_nascimento  102626 non-null  object
 26  email                 9199 non-null    object
 27  raca                  76696 non-null   object
dtypes: float64(5), int64(5), object(18)
memory usage: 22.3+ MB

In [ ]:
df.shape

(104590, 28)

In [ ]:
df.columns

Index(['ano', 'id_eleicao', 'tipo_eleicao', 'data_eleicao', 'sigla_uf',
       'id_municipio', 'id_municipio_tse', 'titulo_eleitoral', 'cpf',
       'sequencial', 'numero', 'nome', 'nome_urna', 'numero_partido',
       'sigla_partido', 'cargo', 'situacao', 'data_nascimento', 'idade',
       'genero', 'instrucao', 'ocupacao', 'estado_civil', 'nacionalidade',
       'sigla_uf_nascimento', 'municipio_nascimento', 'email', 'raca'],
      dtype='object')

In [ ]:
df.groupby('situacao').size()

situacao
aguardando julgamento                                3
cancelado                                           66
cancelado com recurso                                1
cassado                                            201
cassado com recurso                                 26
deferido                                         94523
deferido com recurso                               204
falecido                                            23
falecimento                                          3
indeferido                                        3050
indeferido com recurso                             347
inelegivel                                           5
nao conhecimento do pedido                          24
pedido nao conhecido                                25
pedido nao conhecido com recurso                     2
pendente de julgamento                              15
renuncia                                          1780
sub judice                                          12
substituto majoritario pendente de julgamento        3
dtype: int64

In [ ]:
df.groupby(['ano','id_eleicao','tipo_eleicao']).size()

ano   id_eleicao  tipo_eleicao
1994  1994001     eleicao ordinaria                           680
1996  1996001     eleicao ordinaria                          1216
1998  1998001     eleicao ordinaria                          1726
2002  200201      eleicao ordinaria                          1042
2006  2006001     eleicao ordinaria                          2182
                                                            ...
2020  624         eleicao suplementar de analandia              1
      625         rj - suplementar de armacao dos buzios        1
      629         suplementar sao francisco de assis            1
2022  546         eleicao ordinaria                          1702
2024  619         eleicao ordinaria                         24287
Length: 95, dtype: int64

**Limpar base para conter apenas:**

*   deferido
*   deferido com recurso

In [ ]:
df_deferido = df[(df['situacao'] == 'deferido') | (df['situacao'] == 'deferido com recurso')]

In [ ]:
df_deferido.reset_index(inplace=True)

In [ ]:
df_deferido = df_deferido.drop(columns=['index'])

In [ ]:
df_deferido

,ano,id_eleicao,tipo_eleicao,data_eleicao,sigla_uf,id_municipio,id_municipio_tse,titulo_eleitoral,cpf,sequencial,...,idade,genero,instrucao,ocupacao,estado_civil,nacionalidade,sigla_uf_nascimento,municipio_nascimento,email,raca
0,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,2.145152e+09,3.766489e+09,10309,...,52.0,masculino,ensino superior completo,economista,solteiro(a),brasileira,AC,Tarauacá,chagasfreitas@yahoo.com,NaN
1,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,4.988525e+08,1.965592e+10,10002,...,42.0,masculino,ensino medio completo,outros,casado(a),brasileira,AC,Rio Branco,beniciodias@click21.com.br,NaN
2,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,1.649702e+10,5.079152e+10,10023,...,36.0,feminino,ensino superior completo,outros,casado(a),brasileira,AC,Senador Guiomard,paulo@ufac.br,NaN
3,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,1.426382e+09,2.190710e+09,10031,...,54.0,masculino,ensino superior completo,deputado,casado(a),brasileira,AC,Tarauacá,dep.nilsonmourao@camara.gov.br,NaN
4,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,2.645724e+08,2.163076e+10,10032,...,42.0,masculino,ensino superior completo,deputado,casado(a),brasileira,CE,Cruzeiro Do Sul,dep.henriqueafonso@camara.gov.br,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94722,2008,30,eleicao ordinaria,2008-10-05,RS,4314050.0,98256.0,3.234066e+10,3.706474e+10,10299,...,50.0,masculino,ensino medio completo,servidor publico municipal,casado(a),brasileira,RS,Taquara,NaN,NaN
94723,2008,30,eleicao ordinaria,2008-10-05,RS,4314407.0,87912.0,1.759304e+08,1.033680e+10,18852,...,60.0,masculino,ensino superior incompleto,locutor e comentarista de radio e televisao e ...,casado(a),brasileira,RS,Pelotas,NaN,NaN
94724,2008,30,eleicao ordinaria,2008-10-05,RS,4314902.0,88013.0,2.225345e+10,3.928181e+10,21685,...,46.0,masculino,ensino fundamental completo,cobrador de transporte coletivo,casado(a),brasileira,RS,Porto Alegre,NaN,NaN
94725,2008,30,eleicao ordinaria,2008-10-05,RS,4316808.0,88390.0,4.434063e+10,4.177331e+10,19723,...,50.0,feminino,ensino medio completo,supervisor inspetor e agente de compras e vendas,casado(a),brasileira,RS,Sobradinho,helena40818@bol.com.br,NaN
94726,2008,30,eleicao ordinaria,2008-10-05,RS,4317103.0,88455.0,6.155445e+10,7.296529e+10,16039,...,35.0,feminino,ensino superior completo,advogado,solteiro(a),brasileira,RS,Santana Do Livramento,NaN,NaN

In [ ]:
df_deferido[['numero', 'nome_urna','numero_partido','nome']]

,numero,nome_urna,numero_partido,nome
0,255,Chagas Freitas,25,Francisco Chagas Da Costa Freitas
1,277,Chico Benicio,27,Francisco Chagas Benício Dias
2,1112,Antonia Lúcia,11,Antonia Luciléia Cruz Ramos Câmara
3,1313,Nilson Mourão,13,Nilson Moura Leite Mourão
4,1345,Henrique Afonso,13,Henrique Afonso Soares Lima
...,...,...,...,...
94722,40650,Jose Vilmar Fernandes (Pinto),40,Jose Vilmar Fernandes
94723,40555,Darcy Pino,40,Darcy Pino Da Rosa
94724,40114,Jorge Correa Meio Kilo,40,Jorge Da Costa Correa
94725,40818,Helena Haas,40,Helena Maria Haas
94726,40200,Dra Marcia,40,Marcia Rodrigues Da Silva

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    "sequencial": "sequencial_candidato",
    "titulo_eleitoral": "titulo_eleitoral",
    "id_eleicao": "id_eleicao",
    "numero_partido": "numero_partido",
    "id_municipio": "id_municipio",
    "cargo": "cargo",
    "numero": "numero_urna",
    "nome_urna": "nome_urna",
    "situacao": "situacao"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las
df_deferido_tabela = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).copy()


# Visualizar o resultado
df_deferido_tabela.head()

,sequencial_candidato,titulo_eleitoral,id_eleicao,numero_partido,id_municipio,cargo,numero_urna,nome_urna,situacao
0,10309,2.145152e+09,2006001,25,NaN,senador,255,Chagas Freitas,deferido
1,10002,4.988525e+08,2006001,27,NaN,senador,277,Chico Benicio,deferido
2,10023,1.649702e+10,2006001,11,NaN,deputado federal,1112,Antonia Lúcia,deferido
3,10031,1.426382e+09,2006001,13,NaN,deputado federal,1313,Nilson Mourão,deferido
4,10032,2.645724e+08,2006001,13,NaN,deputado federal,1345,Henrique Afonso,deferido

In [ ]:
df_deferido_tabela.to_csv('candidatos.csv', index=False)

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    "titulo_eleitoral": "titulo_eleitoral",
    "cpf": "cpf",
    "nome": "nome",
    "data_nascimento": "data_nascimento",
    "genero": "genero",
    "raca": "raca"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las
df_deferido_pessoas = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).copy()


# Visualizar o resultado
df_deferido_pessoas.head()

,titulo_eleitoral,cpf,nome,data_nascimento,genero,raca
0,2.145152e+09,3.766489e+09,Francisco Chagas Da Costa Freitas,1955-03-08,masculino,NaN
1,4.988525e+08,1.965592e+10,Francisco Chagas Benício Dias,1964-04-15,masculino,NaN
2,1.649702e+10,5.079152e+10,Antonia Luciléia Cruz Ramos Câmara,1970-07-17,feminino,NaN
3,1.426382e+09,2.190710e+09,Nilson Moura Leite Mourão,1952-04-01,masculino,NaN
4,2.645724e+08,2.163076e+10,Henrique Afonso Soares Lima,1964-12-03,masculino,NaN

In [ ]:
df_deferido_pessoas.to_csv('pessoas.csv', index=False)

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    "id_eleicao": "id_eleicao",
    "ano": "ano",
    "tipo_eleicao": "tipo_eleicao",
    "data_eleicao": "data_eleicao"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las

df_deferido_eleicao = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).drop_duplicates().copy()
df_deferido_eleicao.reset_index(inplace=True)
df_deferido_eleicao = df_deferido_eleicao.drop(columns=['index'])

# Visualizar o resultado
df_deferido_eleicao.head()

   id_eleicao   ano                      tipo_eleicao data_eleicao
0     2006001  2006                 eleicao ordinaria   2006-10-01
1         297  2018                 eleicao ordinaria   2018-10-07
2         438  2018  eleicao suplementar senador - mt   2020-11-15
3         295  2018                 eleicao ordinaria   2018-10-07
4          30  2008                 eleicao ordinaria   2008-10-05

In [ ]:
df_deferido_eleicao.to_csv('eleicao.csv', index=False)

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    "numero_partido": "numero_partido",
    "sigla_partido": "sigla_partido"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las

df_deferido_partido = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).drop_duplicates().copy()
df_deferido_partido.reset_index(inplace=True)
df_deferido_partido = df_deferido_partido.drop(columns=['index'])

# Visualizar o resultado
df_deferido_partido.head()

   numero_partido sigla_partido
0              25           PFL
1              27          PSDC
2              11            PP
3              13            PT
4              23           PPS

In [ ]:
df_deferido_partido.to_csv('partido.csv', index=False)

In [ ]:
df.columns

Index(['ano', 'id_eleicao', 'tipo_eleicao', 'data_eleicao', 'sigla_uf',
       'id_municipio', 'id_municipio_tse', 'titulo_eleitoral', 'cpf',
       'sequencial', 'numero', 'nome', 'nome_urna', 'numero_partido',
       'sigla_partido', 'cargo', 'situacao', 'data_nascimento', 'idade',
       'genero', 'instrucao', 'ocupacao', 'estado_civil', 'nacionalidade',
       'sigla_uf_nascimento', 'municipio_nascimento', 'email', 'raca'],
      dtype='object')

In [ ]:
df_municipio = pd.read_csv('https://raw.githubusercontent.com/danielIESB/Trabalho-Projeto-Eleicao/331f19fb7362f45847f748289f2079447ccf82ee/municipio_tse_ibge.csv', sep=';', encoding='latin1')

In [ ]:
df_municipio.head()

,DT_GERACAO,HH_GERACAO,CD_UF_TSE,CD_UF_IBGE,SG_UF,NM_UF,CD_MUNICIPIO_TSE,NM_MUNICIPIO_TSE,CD_MUNICIPIO_IBGE,NM_MUNICIPIO_IBGE
0,10/05/2026,09:01:10,24,12,AC,Acre,1007,Bujari,1200138,Bujari
1,10/05/2026,09:01:10,24,12,AC,Acre,1015,Capixaba,1200179,Capixaba
2,10/05/2026,09:01:10,24,12,AC,Acre,1023,Porto Acre,1200807,Porto Acre
3,10/05/2026,09:01:10,24,12,AC,Acre,1031,Santa Rosa Do Purus,1200435,Santa Rosa Do Purus
4,10/05/2026,09:01:10,24,12,AC,Acre,1040,Marechal Thaumaturgo,1200351,Marechal Thaumaturgo

In [ ]:
municipio_candidatos = df_deferido[['id_municipio']].drop_duplicates().copy()
municipio_candidatos.reset_index(inplace=True)
municipio_candidatos = municipio_candidatos.drop(columns=['index'])
municipio_candidatos.head()

   id_municipio
0           NaN
1     1100049.0
2     1100098.0
3     1100114.0
4     1100304.0

In [ ]:
df_municipio['CD_MUNICIPIO_IBGE'] = df_municipio['CD_MUNICIPIO_IBGE'].astype(float)
joined_municipios = pd.merge(municipio_candidatos, df_municipio, left_on='id_municipio', right_on='CD_MUNICIPIO_IBGE', how='inner')
display(joined_municipios.head())

,id_municipio,DT_GERACAO,HH_GERACAO,CD_UF_TSE,CD_UF_IBGE,SG_UF,NM_UF,CD_MUNICIPIO_TSE,NM_MUNICIPIO_TSE,CD_MUNICIPIO_IBGE,NM_MUNICIPIO_IBGE
0,1100049.0,10/05/2026,09:01:10,23,11,RO,Rondônia,94,Cacoal,1100049.0,Cacoal
1,1100098.0,10/05/2026,09:01:10,23,11,RO,Rondônia,256,Espigão Do Oeste,1100098.0,Espigão D'Oeste
2,1100114.0,10/05/2026,09:01:10,23,11,RO,Rondônia,159,Jaru,1100114.0,Jaru
3,1100304.0,10/05/2026,09:01:10,23,11,RO,Rondônia,132,Vilhena,1100304.0,Vilhena
4,1100338.0,10/05/2026,09:01:10,23,11,RO,Rondônia,434,Nova Mamoré,1100338.0,Nova Mamoré

In [46]:
joined_municipios = joined_municipios.drop(columns=[
  'DT_GERACAO',
  'HH_GERACAO',
  'CD_UF_TSE',
  'CD_UF_IBGE',
  'NM_UF',
  'CD_MUNICIPIO_IBGE',
  'NM_MUNICIPIO_IBGE'
])
joined_municipios.head()

   id_municipio SG_UF  CD_MUNICIPIO_TSE  NM_MUNICIPIO_TSE
0     1100049.0    RO                94            Cacoal
1     1100098.0    RO               256  Espigão Do Oeste
2     1100114.0    RO               159              Jaru
3     1100304.0    RO               132           Vilhena
4     1100338.0    RO               434       Nova Mamoré

In [47]:
joined_municipios.to_csv('municipios.csv', index=False)